# Generated by Django 4.2.8 on 2023-12-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_states_changed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='states',
            name='changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
