# Generated by Django 4.2.8 on 2023-12-21 19:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_states_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='states',
            name='states',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, size=None),
        ),
    ]
