# Generated by Django 4.2.6 on 2023-11-29 13:31

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, max_length=31, unique=True),
        ),
    ]
