# Generated by Django 4.2.6 on 2023-12-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='states',
            name='changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
